// Generated by CoffeeScript 1.8.0
(function() {
  var boardIsFull, buildBoard, collapseCells, generateTile, getCol, getRow, isGameOver, mergeCells, move, moveIsValid, noValidMoves, printArray, randomCellIndices, randomInt, randomValue, setCol, setRow, showBoard,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  randomInt = function(x) {
    return Math.floor(Math.random() * x);
  };

  randomCellIndices = function() {
    return [randomInt(4), randomInt(4)];
  };

  randomValue = function() {
    var values;
    values = [2, 2, 2, 4];
    return values[randomInt(4)];
  };

  buildBoard = function() {
    return [0, 1, 2, 3].map((function() {
      return [0, 1, 2, 3].map((function() {
        return 0;
      }));
    }));
  };

  generateTile = function(board) {
    var column, row, value, _ref;
    value = randomValue();
    _ref = randomCellIndices(), row = _ref[0], column = _ref[1];
    console.log([row, column]);
    if (board[row][column] === 0) {
      return board[row][column] = value;
    } else {
      return generateTile(board);
    }
  };

  move = function(board, direction) {
    var col, i, newBoard, row, _i;
    newBoard = buildBoard();
    for (i = _i = 0; _i <= 3; i = ++_i) {
      if (direction === 'right' || direction === 'left') {
        row = getRow(i, board);
        row = mergeCells(row, direction);
        row = collapseCells(row, direction);
        setRow(row, i, newBoard);
      } else if (direction === 'down' || direction === 'up') {
        col = getCol(i, board);
        col = mergeCells(col, direction);
        col = collapseCells(col, direction);
        setCol(col, i, newBoard);
      }
    }
    return newBoard;
  };

  getRow = function(r, board) {
    return [board[r][0], board[r][1], board[r][2], board[r][3]];
  };

  getCol = function(c, board) {
    return [board[0][c], board[1][c], board[2][c], board[3][c]];
  };

  setRow = function(row, index, board) {
    return board[index] = row;
  };

  setCol = function(col, index, board) {
    var i, _i, _results;
    _results = [];
    for (i = _i = 0; _i <= 3; i = ++_i) {
      _results.push(board[i][index] = col[i]);
    }
    return _results;
  };

  mergeCells = function(cells, direction) {
    var merge;
    merge = function(cells) {
      var a, b, _i, _j, _ref;
      for (a = _i = 3; _i > 0; a = --_i) {
        for (b = _j = _ref = a - 1; _ref <= 0 ? _j <= 0 : _j >= 0; b = _ref <= 0 ? ++_j : --_j) {
          if (cells[a] === 0) {
            break;
          } else if (cells[a] === cells[b]) {
            cells[a] *= 2;
            cells[b] = 0;
            break;
          } else if (cells[b] !== 0) {
            break;
          }
        }
      }
      return cells;
    };
    if (direction === 'right' || direction === 'down') {
      cells = merge(cells);
    } else if (direction === 'left' || direction === 'up') {
      cells = merge(cells.reverse()).reverse();
    }
    return cells;
  };

  collapseCells = function(cells, direction) {
    cells = cells.filter(function(x) {
      return x !== 0;
    });
    while (cells.length < 4) {
      if (direction === 'right' || direction === 'down') {
        cells.unshift(0);
      } else if (direction === 'left' || direction === 'up') {
        cells.push(0);
      }
    }
    return cells;
  };

  moveIsValid = function(originalBoard, newBoard) {
    var col, row, _i, _j;
    for (row = _i = 0; _i <= 3; row = ++_i) {
      for (col = _j = 0; _j <= 3; col = ++_j) {
        if (originalBoard[row][col] !== newBoard[row][col]) {
          return true;
        }
      }
    }
    return false;
  };

  isGameOver = function(board) {
    return boardIsFull(board) && noValidMoves(board);
  };

  boardIsFull = function(board) {
    var row, _i, _len;
    for (_i = 0, _len = board.length; _i < _len; _i++) {
      row = board[_i];
      if (__indexOf.call(row, 0) >= 0) {
        return false;
      }
    }
    return true;
  };

  noValidMoves = function(board) {
    var direction, directions, newBoard, _i, _len;
    directions = ['right', 'left', 'up', 'down'];
    for (_i = 0, _len = directions.length; _i < _len; _i++) {
      direction = directions[_i];
      newBoard = move(board, direction);
      if (moveIsValid(board, newBoard)) {
        return false;
      }
    }
    return true;
  };

  showBoard = function(board) {
    var col, power, row, _i, _results;
    _results = [];
    for (row = _i = 0; _i <= 3; row = ++_i) {
      _results.push((function() {
        var _j, _k, _results1;
        _results1 = [];
        for (col = _j = 0; _j <= 3; col = ++_j) {
          for (power = _k = 1; _k <= 11; power = ++_k) {
            $(".r" + row + ".c" + col).removeClass('value-' + Math.pow(2, power));
          }
          if (board[row][col] === 0) {
            _results1.push($(".r" + row + ".c" + col + " > div").html(" "));
          } else {
            $(".r" + row + ".c" + col + " > div").html(board[row][col]);
            _results1.push($(".r" + row + ".c" + col).addClass('value-' + board[row][col]));
          }
        }
        return _results1;
      })());
    }
    return _results;
  };

  printArray = function(array) {
    var row, _i, _len;
    console.log("-- Start --");
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      row = array[_i];
      console.log(row);
    }
    return console.log("-- End --");
  };

  $(function() {
    var gameStarted, timePlayedMin, timePlayedSec;
    $('.board').hide();
    $('.board').fadeIn(1000);
    this.board = buildBoard();
    generateTile(this.board);
    generateTile(this.board);
    showBoard(this.board);
    gameStarted = false;
    timePlayedSec = 13;
    timePlayedMin = 0;
    $('.newGame').click((function(_this) {
      return function() {
        return document.location.reload();
      };
    })(this));
    setInterval((function(_this) {
      return function() {
        if ((timePlayedSec === 0) && (timePlayedMin === 0)) {
          $('.timer').addClass('stopPlaying').html('STOP!');
          return $('h1 p > span').addClass('addicts').html('ADDICT!');
        } else if ((timePlayedSec === 11) && (timePlayedMin === 0)) {
          $('.board').addClass('stopPlayingBoard').fadeOut(800).fadeIn(800).fadeOut(700).fadeIn(700).fadeOut(600).fadeIn(600).fadeOut(500).fadeIn(500).fadeOut(400).fadeIn(400).fadeOut(350).fadeIn(350).fadeOut(300).fadeIn(300).fadeOut(250).fadeIn(250).fadeOut(200).fadeIn(200).fadeOut(150).fadeIn(150).fadeOut(100).fadeIn(100).fadeOut(100).fadeIn(100).fadeOut(100).fadeIn(100).fadeOut(100).fadeIn(100).fadeOut(100).fadeIn(50).fadeOut();
          timePlayedSec -= 1;
          if (timePlayedSec === -1) {
            timePlayedSec = 59;
            timePlayedMin -= 1;
          }
          $('.timer > p').html("" + timePlayedMin + ":" + timePlayedSec);
          return $('.newGame').click(function() {
            return alert('Don\'t even think about it!');
          });
        } else if (gameStarted) {
          timePlayedSec -= 1;
          if (timePlayedSec === -1) {
            timePlayedSec = 59;
            timePlayedMin -= 1;
          }
          return $('.timer > p').html("" + timePlayedMin + ":" + timePlayedSec);
        }
      };
    })(this), 1000);
    return $('body').keydown((function(_this) {
      return function(e) {
        var direction, key, keys, newBoard;
        key = e.which;
        keys = [37, 38, 39, 40];
        if (__indexOf.call(keys, key) >= 0) {
          gameStarted = true;
          e.preventDefault();
          direction = (function() {
            switch (key) {
              case 37:
                return 'left';
              case 38:
                return 'up';
              case 39:
                return 'right';
              case 40:
                return 'down';
            }
          })();
          console.log(direction);
          newBoard = move(_this.board, direction);
          printArray(newBoard);
          if (moveIsValid(_this.board, newBoard)) {
            console.log("valid");
            _this.board = newBoard;
            generateTile(_this.board);
            showBoard(_this.board);
            if (isGameOver(_this.board)) {
              return console.log("You LOSE!");
            } else {

            }
          } else {
            return console.log("invalid");
          }
        }
      };
    })(this));
  });

}).call(this);

//# sourceMappingURL=main.js.map
