// Generated by CoffeeScript 1.8.0
(function() {
  var buildBoard, generateTile;

  buildBoard = function() {
    return console.log("build board");
  };

  generateTile = function() {
    return console.log("generate tile");
  };

  $(function() {
    buildBoard();
    generateTile();
    return generateTile();
  });

}).call(this);

//# sourceMappingURL=main.js.map
